# Generated by Django 5.0.6 on 2026-04-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_events", models.IntegerField(default=0)),
                ("recognized", models.IntegerField(default=0)),
                ("unknown", models.IntegerField(default=0)),
                ("spoofing_attempts", models.IntegerField(default=0)),
                ("unique_persons", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Денна статистика",
                "verbose_name_plural": "Денна статистика",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecognitionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("recognized", "Розпізнано"),
                            ("unknown", "Невідома особа"),
                            ("spoofing", "Спроба підробки"),
                            ("multi_face", "Декілька облич"),
                            ("low_quality", "Низька якість кадру"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("liveness_score", models.FloatField(blank=True, null=True)),
                (
                    "frame_snapshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/%Y/%m/%d/"
                    ),
                ),
                (
                    "face_crop",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/faces/%Y/%m/"
                    ),
                ),
                ("face_bbox_json", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("is_alert", models.BooleanField(default=False)),
                ("alert_sent", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="cameras.camera",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="persons.person",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подія розпізнавання",
                "verbose_name_plural": "Події розпізнавання",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="events_reco_timesta_6e3501_idx"
                    ),
                    models.Index(
                        fields=["camera", "timestamp"],
                        name="events_reco_camera__76da18_idx",
                    ),
                    models.Index(
                        fields=["person", "timestamp"],
                        name="events_reco_person__3f7e03_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="events_reco_event_t_098786_idx"
                    ),
                    models.Index(
                        fields=["is_alert", "alert_sent"],
                        name="events_reco_is_aler_7e5a4e_idx",
                    ),
                ],
            },
        ),
    ]
