# Generated by Django 5.0.6 on 2026-04-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="persons.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підрозділ",
                "verbose_name_plural": "Підрозділи",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="По батькові"
                    ),
                ),
                (
                    "person_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID (табельний номер)"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Персонал"),
                            ("visitor", "Відвідувач"),
                            ("contractor", "Підрядник"),
                            ("unknown", "Невідомий"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "access_level",
                    models.IntegerField(default=1, verbose_name="Рівень доступу (1-5)"),
                ),
                (
                    "primary_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="persons/",
                        verbose_name="Основне фото",
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_requested", models.BooleanField(default=False)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="persons.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особа",
                "verbose_name_plural": "Особи",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="FaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encoding_data", models.BinaryField()),
                ("model_version", models.CharField(default="resnet_v1", max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encodings",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Encoding",
                "verbose_name_plural": "Face Encodings",
            },
        ),
        migrations.CreateModel(
            name="PersonPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="persons/training/", verbose_name="Фото"
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("face_detected", models.BooleanField(null=True)),
                ("encoding", models.BinaryField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("landmarks_json", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото особи",
                "verbose_name_plural": "Фото осіб",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["person_id"], name="persons_per_person__841620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faceencoding",
            index=models.Index(
                fields=["person", "is_primary"], name="persons_fac_person__9e1ea6_idx"
            ),
        ),
    ]
