# Generated by Django 5.0.6 on 2026-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceencoding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="faceencoding",
            name="encoding_data",
            field=models.BinaryField(verbose_name="Зашифрований вектор ознак"),
        ),
        migrations.AlterField(
            model_name="faceencoding",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Основний encoding"),
        ),
        migrations.AlterField(
            model_name="faceencoding",
            name="model_version",
            field=models.CharField(
                default="resnet_v1", max_length=50, verbose_name="Версія моделі"
            ),
        ),
    ]
