# Generated by Django 5.0.6 on 2026-04-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpoofingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attack_type",
                    models.CharField(
                        choices=[
                            ("photo", "Фото-атака"),
                            ("video", "Відео-атака"),
                            ("unknown", "Невідомий тип"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("ear_value", models.FloatField(blank=True, null=True)),
                ("texture_score", models.FloatField(blank=True, null=True)),
                ("depth_score", models.FloatField(blank=True, null=True)),
                (
                    "frame_evidence",
                    models.ImageField(
                        blank=True, null=True, upload_to="security/spoofing/"
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spoofing_attempts",
                        to="cameras.camera",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spoofing_detail",
                        to="events.recognitionevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спроба Spoofing",
                "verbose_name_plural": "Спроби Spoofing",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("details_json", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит лог",
                "verbose_name_plural": "Аудит логи",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="security_au_user_id_88bbbb_idx",
                    )
                ],
            },
        ),
    ]
