# Generated by Django 5.0.6 on 2026-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spoofingattempt",
            name="final_module_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="spoofingattempt",
            name="final_reason_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="spoofingattempt",
            name="final_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
