# Generated by Django 5.0.6 on 2026-04-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Назва")),
                (
                    "location",
                    models.CharField(max_length=500, verbose_name="Розташування"),
                ),
                (
                    "camera_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код камери"
                    ),
                ),
                (
                    "stream_url",
                    models.CharField(
                        max_length=500,
                        verbose_name="URL потоку (rtsp:// або 0,1,2 для USB)",
                    ),
                ),
                (
                    "is_local",
                    models.BooleanField(default=True, verbose_name="Локальна (USB)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("offline", "Офлайн"),
                            ("maintenance", "Обслуговування"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                (
                    "recognition_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Розпізнавання ввімкнено"
                    ),
                ),
                (
                    "detection_confidence",
                    models.FloatField(
                        default=0.55, verbose_name="Поріг впевненості (0.0-1.0)"
                    ),
                ),
                (
                    "frame_skip",
                    models.IntegerField(
                        default=2, verbose_name="Обробляти кожен N-й кадр"
                    ),
                ),
                (
                    "resolution_scale",
                    models.FloatField(
                        default=0.25, verbose_name="Масштаб для ML (0.25 = чверть)"
                    ),
                ),
                (
                    "access_zone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Зона доступу"
                    ),
                ),
                (
                    "requires_mfa",
                    models.BooleanField(default=False, verbose_name="Потребує MFA"),
                ),
            ],
            options={
                "verbose_name": "Камера",
                "verbose_name_plural": "Камери",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CameraZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("x2", models.FloatField()),
                ("y2", models.FloatField()),
                (
                    "trigger_alert",
                    models.BooleanField(
                        default=False, verbose_name="Тригер сповіщення при вході в зону"
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона камери",
                "verbose_name_plural": "Зони камер",
            },
        ),
    ]
