# Generated by Django 5.0.6 on 2026-04-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Назва")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("attendance", "Відвідуваність"),
                            ("unknown_persons", "Невідомі особи"),
                            ("security_audit", "Аудит безпеки"),
                            ("daily_summary", "Денний підсумок"),
                            ("custom", "Власний"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("xlsx", "Excel")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("params_json", models.JSONField(default=dict)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("generating", "Генерується"),
                            ("ready", "Готово"),
                            ("failed", "Помилка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Звіт",
                "verbose_name_plural": "Звіти",
                "ordering": ["-created_at"],
            },
        ),
    ]
